### PR TITLE
Build flow

### PR DESCRIPTION
**Pull request by jeffries**
Add build flow based on Gulp, Babel, and JSHint. Also switch to Yarn for dependencies. 

Build is currently configured to fail if linting fails, and to run transpilation and linting concurrently.

Updates repository structure to more clearly differentiate between source code, transpiler output, and tests.

Includes PR #22

### CODE REVIEW

**Review by psiemens — APPROVED** [review]
The code looks good to me.

One thing: can we add a task to the gulpfile for running the server? Doesn't have to happen for this PR, but would be nice to do `gulp run` or something like that.

**Comment by stanleyye** [comment]
seems pretty good to me. Also gulp clean is deprecated but it still works so thats fine. I assume you've tested this right?

**Comment by jeffries** [comment]
@stanleyye I have indeed

**Comment by jeffries** [comment]
@stanleyye you're right, I didn't mean to push that bit. Will remove.

**Comment by stanleyye** [comment]
I think its fine if you keep it, someone may need to delete the target directory for whatever reason but then again you can just delete the directory instead of running a gulp task to delete it. I would personally keep it since we are doing this for development work

**Pull request merged**
