### PR TITLE
Heroku deployment

### PR DESCRIPTION
**Pull request by stanleyye**
Not sure on what version of Node we will be sticking to.

### CODE REVIEW

**Comment by psiemens** [comment]
My only concern with this is that we have multiple Node servers in this repo, but Heroku typically expects one server per repository. 

We might want to look into splitting our architecture across three separate repos. 

Thoughts? @agentfll @stanleyye

**Comment by stanleyye** [comment]
yup, seems like heroku only supports 1 process per dyno. Also, we are only limited to a maximum of 2 concurrent running free dynos, aka we can't run all three APIs concurrently.  This could be a problem

**Comment by psiemens** [comment]
@stanleyye If we need it, I can get us on a paid Heroku plan.

However, only two of our projects are APIs -- the third is just client-side -- so we should be good

**Comment by jeffries** [comment]
@psiemens I've been wondering if we really need a multi-service architecture for this—I doubt that at any point we'll see enough load on the management application to necessitate a separate service for it, especially considering the additional complexity

**Pull request closed without merging**
